# Generated by Django 5.2.9 on 2026-03-20 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_customer_options_remove_customer_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"permissions": [("cancel_order", "Can cancel order")]},
        ),
    ]
